tmdb:
  api:
    key: ${TMDB_API_KEY}
  base:
    url: https://api.themoviedb.org/3

host:
  ip: ${HOST_IP}

server:
  port: 8080
api:
  version: @project.version@
spring:
  application:
    name: poc-demo

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    operationsSorter: method

openapi:
  info:
    version: @project.version@
    description: API rest demo with spring
    title: API DEMO
